twitter:
  OAuthHandler:
    consumer_key:
    consumer_secret:
  access_token:
    key:
    secret:
chain:
  url: wss://polkadot.api.onfinality.io/public-ws
  ss58_format: 0
  type_registry_preset: polkadot
alert:
  transact_threshold: 10000
  whale_threshold: 500000
github:
  repository: https://api.github.com/repos/paritytech/polkadot/releases/latest